//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploBursatil.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indices
    {
        public int ID { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Apertura { get; set; }
        public double Mínimo { get; set; }
        public double Máximo { get; set; }
        public double Último { get; set; }
        public double Stock3 { get; set; }
        public double Stock6 { get; set; }
        public double RSI { get; set; }
        public double Tendencia { get; set; }
        public string Especie { get; set; }
        public double Volumen { get; set; }
        public double Stock { get; set; }
    }
}
